h5_file: 'HSM_dain_more.h5' # Change to your directory 
evaluate_view: 'data/evaluation_view.npy'
model_pretrain_G: '/root/data/final_model/mask_prev/netG_epoch006.pth'
model_pretrain_D: '/root/data/final_model/mask_prev/netD_epoch006.pth'
#model_pretrain_G: '/root/share/Image_Generator_aug/checkpoints/full_train/checkpoints/netG_epoch060.pth'
#model_pretrain_D: '/root/share/Image_Generator_aug/checkpoints/full_train/checkpoints/netD_epoch060.pth'
optimizer: ''

##############################
#    Optimizer parameters    # 
##############################
nr_epochs: 200
lr_policy: step                  # learning rate scheduler [multistep|constant|step]
beta1: 0.0                       # Adam hyperparameter
beta2: 0.999                     # Adam hyperparameter
gamma: 0.5                       # Learning Rate Decay
weight_decay: 0.0005             # weight decay
step_size: 4                    # epochs to decay the learning rate by gamma
lr: 0.00001                       # initial model learning rate
lr_d: 0.00004                     # initial discriminator learning rate

##################################
#    Visualization parameters    # 
##################################

display_freq: 20
print_freq: 200

eval_step: 1
save_step: 1
num_image: 1
update_frame_step: 2

##############################
#     Pose generator        # 
##############################

Gen:
    input_nc: [9, 66]
    output_nc: [3, 1]
    ngf: 32
    init: 'normal'
    norm: 'instance'
    dropout: False    
    n_blocks: 6
    padding: 'reflect'
    use_tanh: True
    n_downsampling: 4
    final_layer: 3

gen:  
    num_frames_G: 2
    input_image_nc: 3
    input_label_nc: 22
    num_filters: 16
    max_num_filters: 512
    num_layers: 6
    num_downsamples: 4
    kernel_size: 3
    activation_norm_type: spatially_adaptive
    activation_norm_params:
        activation_norm_type: instance
        num_filters: 0
        kernel_size: 1
    weight_norm_type: spectral
    do_checkpoint: True
    mask:
        generate_raw_output: False
        num_filters: 32
        max_num_filters: 512
        num_downsamples: 3
        num_res_blocks: 4
        kernel_size: 3
        activation_norm_type: instance
        weight_norm_type: spectral
    embed:
        use_embed: True
        arch: encoder
        num_filters: 64
        max_num_filters: 512
        num_downsamples: 4
        kernel_size: 3
        weight_norm_type: spectral

##############################
#     Image Discriminator    # 
##############################
dis:
    input_image_nc: 3
    input_label_nc: 22
    num_frames_D: 2
    few_shot: False
    type: imaginaire.discriminators.fs_vid2vid
    image:
        num_filters: 32
        max_num_filters: 512
        num_discriminators: 2
        num_layers: 4
        weight_norm_type: spectral
        activation_norm_type: instance
    additional_discriminators:
        face:
            num_filters: 32
            max_num_filters: 512
            num_discriminators: 1
            num_layers: 3
            weight_norm_type: spectral
            activation_norm_type: instance
            loss_weight: 10.0
            crop_func: utils.utils::crop_face_from_output
            vis: imaginaire.model_utils.fs_vid2vid::get_face_bbox_for_output
        hand:
           num_filters: 32
           max_num_filters: 512
           num_discriminators: 1
           num_layers: 3
           weight_norm_type: spectral
           activation_norm_type: instance
           loss_weight: 10.0
           crop_func: utils.utils::crop_hand_from_output
           vis: imaginaire.model_utils.fs_vid2vid::get_hand_bbox_for_output


##############################
#   Loss function param s    # 
##############################
gan_mode: hinge

# loss for using peerceptual loss
perceptual:
    weight: 10.0
    model: vgg19
    layers:
      - 'relu_1_1'
      - 'relu_2_1'
      - 'relu_3_1'
      - 'relu_4_1'
      - 'relu_5_1'
    weights:
      - 0.03125
      - 0.0625
      - 0.125
      - 0.25
      - 1.0
    criterion: 'l1'
    num_scales: 1
gan:
    fuse: 0.0
    raw: 1.0
    face: 0.1
    hand: 0.1

fm_w: 1.0
l1_w: 30.0
mask_w: 5.0

###################################
#    Evaluation setting    # 
###################################
test_gen_mode: 'previous'     #  keyframe | previous | two_frame
gen_videos: true

###################################
#    Dataset motion setting    # 
###################################
train_video_list: [
                   '00_Dance_001', '00_Dance_002', '00_Dance_003', '00_Dance_004', '00_Dance_005',
                   '01_Dance_011', '01_Dance_012', '01_Dance_013', '01_Dance_014', '01_Dance_015',
                   '02_Boxing_104', '02_Boxing_104', '02_Boxing_104', '02_Boxing_104',
                   '03_Boxing_111', '03_Boxing_112', '03_Boxing_113', '03_Boxing_114', '03_Boxing_115', '03_Boxing_116',
                   '03_Boxing_117', '03_Boxing_119', '03_Boxing_120', '03_Boxing_121', '03_Boxing_122',
                   '04_Basketball_201', '04_Basketball_202', '04_Basketball_203', '04_Basketball_204', '04_Basketball_205',
                   '04_Basketball_206', '04_Basketball_207', '04_Basketball_208', '04_Basketball_209', '04_Basketball_210',
                   '04_Basketball_211', '04_Basketball_212', '04_Basketball_213', 
                   '05_Body_301', '05_Body_302', '05_Body_303', '05_Body_304', '05_Body_305',
                   '05_Body_306', '05_Body_307', '05_Body_308', '05_Body_309', '05_Body_310',
                   '06_Body_311', '06_Body_312', '06_Body_313', '06_Body_314', '06_Body_315',
                   '06_Body_316', '06_Body_317', '06_Body_318', '06_Body_319', '06_Body_320',
                   '07_Body_321', '07_Body_322', '07_Body_323', '07_Body_324', '07_Body_325', 
                   '08_Kungfu_401', '08_Kungfu_402', '08_Kungfu_403', '08_Kungfu_404', '08_Kungfu_405',
                   '08_Kungfu_406', '08_Kungfu_407', '08_Kungfu_408', '08_Kungfu_409', '08_Kungfu_410',
                   '08_Kungfu_411', '08_Kungfu_412', '08_Kungfu_413', '08_Kungfu_414', '08_Kungfu_415',
                   '09_Kungfu_421', '09_Kungfu_422', '09_Kungfu_423', '09_Kungfu_424', '09_Kungfu_425', '09_Kungfu_426',
                   '09_Kungfu_427', '09_Kungfu_428', '09_Kungfu_429', '09_Kungfu_430', '09_Kungfu_431',
                   '10_Kungfu_441', '10_Kungfu_442', 
                   '11_Kungfu_451'
                    ]
test_video_list : ['test_004', 'test_006', 'test_106', 'test_112', 'test_204', 'test_301', 'test_312', 'test_314', 'test_404' ,'test_409', 'test_413', 'test_415']
eval_frames: 40

max_frames: 4
sampling_mode: 'neighbor'
random_drop_prob: 0.02
random_blur_rate: 0.06
gauss_sigma: 5
skeleton_thres: 0.001
foot_thres: 0.001

load_width: 480
load_height: 320

model_width: 480
model_height: 320

